spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_service
    username: sheru
    password: Shreyans@2801
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
